default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Activek123?
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: motorbike_back_end_development

test:
  <<: *default
  database: motorbike_back_end_test

production:
  <<: *default
  database: motorbike_back_end_production
  username: motorbike_back_end
  password: <%= ENV["MOTORBIKE_BACK_END_DATABASE_PASSWORD"] %>
