default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Siphose1
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: motorbike_back_end_development

test:
  <<: *default
  database: motorbike_back_end_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
